### ISSUE TITLE
Question about ExportAllSharesAndSizes.ps1

### ISSUE THREAD

**Issue by manfredfessl** [nasuni-labs/nasuni-api-utilities#10]
Hello everyone,

my company is a Nasuni customer in Europe, we plan to use the script ExportAllSharesAndSizes.ps1 for charging of share sizes to our customer.
I am not an experienced user of the GitHub community nor scripter, so please bear with me :-)

I hope you can help me with some issues I have when executing the script.
I adjusted the script in the following points and left the rest untouched:

- fixed $hostname
- fixed $username
- fixed secure password
- changed $reportFile to specific path
- changed $limit to value of 3000 (because we have more than 1500 shares)

Now the script generally works and generates output for many shares, but intermittently I receive error messages for some shares.
Please note that the errors occur on different shares each time I run the script,  I also verified the errors and could access the shares manually in Windows Explorer, there doesn't seem to be an issue with the shares configuration.

It seems that up to ~100 shares can be processed without issues, then I get some errors in between, then it continues to run well, only to see further errors after a while.

Here are the different types of errors I get:

Invoke-RestMethod : The remote server returned an error: (404) Not Found.
At D:\BackupTeam_AT\Nasuni\Postman\Script\reports\ExportAllSharesAndSizes.ps1:109 char:17
+ ... tPathInfo = Invoke-RestMethod -Uri $GetPathInfoURL -Method Get -Heade ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The request was aborted: The request was canceled.
At D:\BackupTeam_AT\Nasuni\Postman\Script\reports\ExportAllSharesAndSizes.ps1:109 char:17
+ ... tPathInfo = Invoke-RestMethod -Uri $GetPathInfoURL -Method Get -Heade ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Invoke-RestMethod : The request was aborted: Could not create SSL/TLS secure channel.
At D:\BackupTeam_AT\Nasuni\Postman\Script\reports\ExportAllSharesAndSizes.ps1:109 char:17
+ ... tPathInfo = Invoke-RestMethod -Uri $GetPathInfoURL -Method Get -Heade ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

After roughly 2 hours runtime I receive the following message, but I guess this will be due to the token being expired?

Invoke-RestMethod : The remote server returned an error: (401) Unauthorized.
At D:\BackupTeam_AT\Nasuni\Postman\Script\reports\ExportAllSharesAndSizes.ps1:103 char:21
+ ... reshStats = Invoke-RestMethod -Uri $GetPathInfoURL -Method POST -Head ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
 
Invoke-RestMethod : The remote server returned an error: (401) Unauthorized.
At D:\BackupTeam_AT\Nasuni\Postman\Script\reports\ExportAllSharesAndSizes.ps1:109 char:17
+ ... tPathInfo = Invoke-RestMethod -Uri $GetPathInfoURL -Method Get -Heade ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

I hope you can support me to make this script run stable in our environment.

Thanks a lot!

Kind Regards,
Manfred Fessl

**Comment by cdillahunty-nasuni** [comment]
Hello Manfred,

I'm sorry for not getting back to you sooner. The intermittent errors are not a script issue since they don't happen for the same shares across multiple executions of the script. They are likely an out-of-memory issue on one of the Edge Appliances or the NMC. I'll make sure to send you an email so that we can do further troubleshooting.

Tokens expire after 8 hours by default, although we can increase that on the backend. I could also help write some PowerShell that detects the expiration and makes another call for a new token to get around the issue.

**Comment by manfredfessl** [comment]
Thank you Coan!
I followed up with an email.
