### ISSUE TITLE
Please add an endpoint for getting all shared links of the whole system

### ISSUE THREAD

**Issue by BerndGewehr** [nasuni-labs/nasuni-api-utilities#11]
The NMC is capable of displaying a table of all shared links on the system. We have re-engineered that to build our own api endpoint for this important information that we use for visualizing every shared link in an Infopage about the project (besides other tools used).

Could you please consider to offer such an API endpoint within the NMC api? That would allow us to rely on your public features rather than having „cool hacks“ in the productive use.

**Comment by cdillahunty-nasuni** [comment]
@BerndGewehr , thank you for the recommendation. We eventually want to expose all NMC features using the NMC API--shared links is something we can evaluate for future inclusion in the NMC API although it would most likely be for Nasuni Access Anywhere Shared links and not the legacy Nasuni Web Access Shared Links functionality.
