### ISSUE TITLE
We are unable to run enable Previous Version script 

### ISSUE THREAD

**Issue by Vipul10111987** [nasuni-labs/nasuni-api-utilities#12]
We are getting the below error while running the script
[https://github.com/nasuni-labs/nasuni-api-utilities/blob/main/Access_Points/Shares/EnablePreviousVersionsForAllShares.ps1](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnasuni-labs%2Fnasuni-api-utilities%2Fblob%2Fmain%2FAccess_Points%2FShares%2FEnablePreviousVersionsForAllShares.ps1&data=05%7C01%7CVipul.Malhotra%40novachem.com%7C6d486cd3b61b41a8cbcb08db4bea6aec%7C0d396c31441f4e16a6e63b017f2f63d1%7C1%7C0%7C638187242428279381%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qllQCMCvlY32OUZOz5eHyPW3cgE%2FKsobB4gedMF7LbA%3D&reserved=0)

![image](https://user-images.githubusercontent.com/132484805/235981275-65845608-39c9-4f8c-9ae7-826067478317.png)

**Comment by cdillahunty-nasuni** [comment]
@Vipul10111987 Have you followed the recommendations in the [basics section](https://github.com/nasuni-labs/nasuni-api-utilities#powershell-rest-api-basics) of the NMC API documentation? The user must be a member of a group that can request and NMC API token and has permission to perform the activity you are requesting.

You can also test with the https://github.com/nasuni-labs/nasuni-api-utilities#request-a-token script to see if that works--if it doesn't something basic needs to be resolved first.

**Comment by Vipul10111987** [comment]
Hello
User is already a member of NMC, We have received a share creation script from Nasuni which is already working fine with same user?
Is it okay if we can arrange a call to fix this error ?

**Comment by Vipul10111987** [comment]
Hello Coan,

I am not very sure, if your email address is correctly marked,  User is already a part of NMC , and with the help of same user we are running other scripts like share creation.
If possible, can we have a call to discuss.

Regards, Vipul Malhotra
________________________________
From: Coan Dillahunty ***@***.***>
Sent: 04 May 2023 03:02
To: nasuni-labs/nasuni-api-utilities ***@***.***>
Cc: Vipul Malhotra ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [nasuni-labs/nasuni-api-utilities] We are unable to run enable Previous Version script (Issue #12)


ATTENTION: This is from an External E-mail Address.
Do not open attachments or click on links unless you recognize the sender and know the content is safe.



@Vipul10111987<https://github.com/Vipul10111987> Have you followed the recommendations in the basics section<https://github.com/nasuni-labs/nasuni-api-utilities#powershell-rest-api-basics> of the NMC API documentation? The user must be a member of a group that can request and NMC API token and has permission to perform the activity you are requesting.

You can also test with the https://github.com/nasuni-labs/nasuni-api-utilities#request-a-token script to see if that works--if it doesn't something basic needs to be resolved first.

**Comment by cdillahunty-nasuni** [comment]
Arranged a call to fix the issue. The script as written updates all shares. Helped Vipul update the script to filter the update so that it only updates shares on a specified edge appliance.
