### ISSUE TITLE
Paths Scripts not using tokens or logging in

### ISSUE THREAD

**Issue by dracodoom** [nasuni-labs/nasuni-api-utilities#16]
I am attempting to use the path scripts to generate automated jobs of bringing lots of subfolders to a local filer.  From my understanding, I need the GetPathInfo script to work as well to get the information for the BringPathIntoCache job to work.  We already have attempted to use the GUI but due to backend restrictions on the function, we have to bring in the subfolders as there are too many files for the GUI process to work as there is CAP on how many files can be downloaded in a job and no way to audit the process.   I have a great many concerns about that process works but these scripts might allow me not to waste days selecting subfolders and telling them to Bring to Cache one by one.

**Comment by cdillahunty-nasuni** [comment]
Hello,
The path scripts/NMC API endpoint can be used to bring paths into cache like you're doing--the best way to monitor to see if the job has finished running is to look for the notification that gets logged in https://docs.api.nasuni.com/api/nmc/v120/reference/tag/Notifications/paths/~1notifications~1/get/.

Using the Get Path Info endpoint to determine cache status for a folder and subfolders is problematic and is getting removed in the K release--it reports true (in cache) if only some of the files/folders are cached.

**Comment by dracodoom** [comment]
Invoke-RestMethod : {"error":{"code":"error","description":"Authentication credentials were not provided."}}
At C:\temp\GetPathInfo.ps1:66 char:10
+ $Refresh=Invoke-RestMethod -Uri $PathInfoURL -Method POST -Headers $h ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Invoke-RestMethod : {"error":{"code":"error","description":"Authentication credentials were not provided."}}
At C:\temp\GetPathInfo.ps1:72 char:12
+ $getinfo = Invoke-RestMethod -Uri $PathInfoURL -Method Get -Headers $ ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Folder Path:  /AMB Data/AMB-WPF_ENG_Working/Working Folder - Unshipped Units/3. Completed Units/600000 - 649999

**Comment by dracodoom** [comment]
Can the scripts be updated to use tokens like the newer ones?

**Comment by dracodoom** [comment]
Getting the following error message when running the GetPathInfo script.  Can it and bring to cache be updated to use tokens like the other newer scripts

PS C:\temp> .\GetPathInfo.ps1
Invoke-RestMethod : {"error":{"code":"error","description":"Authentication credentials were not provided."}}
At C:\temp\GetPathInfo.ps1:66 char:10
+ $Refresh=Invoke-RestMethod -Uri $PathInfoURL -Method POST -Headers $h ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Invoke-RestMethod : {"error":{"code":"error","description":"Authentication credentials were not provided."}}
At C:\temp\GetPathInfo.ps1:72 char:12
+ $getinfo = Invoke-RestMethod -Uri $PathInfoURL -Method Get -Headers $ ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Folder Path:  /AMB Data/AMB-WPF_ENG_Working/Working Folder - Unshipped Units/3. Completed Units/600000 - 649999



From: Coan Dillahunty ***@***.***>
Sent: Tuesday, September 26, 2023 8:28 AM
To: nasuni-labs/nasuni-api-utilities ***@***.***>
Cc: Charles Kearney ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [nasuni-labs/nasuni-api-utilities] Paths Scripts not using tokens or logging in (Issue #16)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hello,
The path scripts/NMC API endpoint can be used to bring paths into cache like you're doing--the best way to monitor to see if the job has finished running is to look for the notification that gets logged in https://docs.api.nasuni.com/api/nmc/v120/reference/tag/Notifications/paths/~1notifications~1/get/.

Using the Get Path Info endpoint to determine cache status for a folder and subfolders is problematic and is getting removed in the K release--it reports true (in cache) if only some of the files/folders are cached.

-

**Comment by cdillahunty-nasuni** [comment]
I'm sorry--I didn't understand your original request. I've updated all the path related scripts to use the tokenFile rather than username and password for authentication.

**Comment by dracodoom** [comment]
Coan, can the bringintocache script be made to use a CSV?  A one off bring into cache through the UI is easy enough, but when we need to bring in multiple subfolders through out a share the gui is very cumbersome.

From: Coan Dillahunty ***@***.***>
Sent: Tuesday, September 26, 2023 4:36 PM
To: nasuni-labs/nasuni-api-utilities ***@***.***>
Cc: Charles Kearney ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [nasuni-labs/nasuni-api-utilities] Paths Scripts not using tokens or logging in (Issue #16)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

I'm sorry--I didn't understand your original request. I've updated all the path related scripts to use the tokenFile rather than username and password for authentication.

-

**Comment by cdillahunty-nasuni** [comment]
closing since the original issue was resolved
