### ISSUE TITLE
get status of operation

### ISSUE THREAD

**Issue by maccardo** [nasuni-labs/nasuni-api-utilities#17]
How do I monitor the status of a long running operation such as pinning folder meta data?

**Comment by cdillahunty-nasuni** [comment]
Pinning is not usually a long-running operation, as pinning is only a setting for a path that lets the system know that it should not evict items within that path from the cache. Pinning does not cause items that are not in the cache to be retrieved from the cloud. Bring into cache or autocache are two options that do that.

If you want to monitor if the system has processed a request to pin the path, use the message id from the pinning request and query the [Get Message endpoint](https://docs.api.nasuni.com/api/nmc/v120/reference/tag/Messages/paths/~1messages~1%7Bmessage_id%7D~1/get/) to see the status. A "pending" message is still being processed, while a "synced" message has completed processing.

**Comment by maccardo** [comment]
Thankyou for your comment, I wanted to restate I was not making reference to pining file data but rather pinning folder meta-data for an entire volume and hence my question of how to monitor metadata pining progress.  Do you have a quick sample code snippet for the montiroing of pinning procegress?

**Comment by cdillahunty-nasuni** [comment]
We don't provide an API mechanism to track how long it takes either form of pinning (data or metadata) requests to take. From the API's perspective, requests are waiting to be picked up (pending) or have started processing (synced). My recommendation is to open a Support case for more insight.
