### ISSUE TITLE
DisableGFL results in Internal server error

### ISSUE THREAD

**Issue by github-hanson** [nasuni-labs/nasuni-api-utilities#18]
When I attempt to run DisableGFL on a path. I get met with this error:
<img width="598" alt="gfl_error" src="https://github.com/nasuni-labs/nasuni-api-utilities/assets/88440126/9946287b-c966-415a-8e14-cee815e564b6">
How should I proceed?

**Comment by cdillahunty-nasuni** [comment]
Can you try again using PowerShell 7 and see if you get the same error?

**Comment by github-hanson** [comment]
I get that same error:
![image](https://github.com/nasuni-labs/nasuni-api-utilities/assets/88440126/14f35702-ab45-42a1-87fe-4d8eb31ddb0f)

**Comment by cdillahunty-nasuni** [comment]
Can you provide these lines from your script (lines 16-23)?

#specify Volume GUID
$volume_guid = "InsertVolumeGuidHere"

#specify Filer Serial Number
$filer_serial_number = "InsertFilerSerialHere"

#specify folder path using slashes (/) - do not include a trailing slash
$path = "/Share-1/Folder-1/Text_files"

**Comment by github-hanson** [comment]
#specify Volume GUID
$volume_guid = "61242b1a-abb3-4a14-a006-f2cb339cd88e_0"

#specify Filer Serial Number
$filer_serial_number = "0ec98b3e-bb0e-4a2f-bdd6-01890cc876a5"

#specify folder path using slashes (/) - do not include a trailing slash 
$path = "/ProductionData/data/24jobs/24TEST_00/CAD"

**Comment by cdillahunty-nasuni** [comment]
Thank you. Can you turn on remote support for your NMC and this NEA so I can troubleshoot further? My first guess is that the path you have might be relative to a share when it needs to be the path relative to the volume (the same way paths are displayed in the NMC file browser).

**Comment by github-hanson** [comment]
Remote support is enabled. Thanks in advance!

**Comment by cdillahunty-nasuni** [comment]
Did you get it working? I'm seeing lots of 202s in the latest NMC API logs, which is expected. If we need to do further troubleshooting, I can arrange a zoom meeting.

**Comment by github-hanson** [comment]
Those might be coming from an application that sets the GFL mode, not from one that takes it away.
________________________________

**Comment by cdillahunty-nasuni** [comment]
My apologies for the delay in getting back to you. If the 202s are from setting GFL and there are still errors turning off GFL, then we need to look at this with you over Zoom. You can email me at cdillahunty@nasuni.com, and we can coordinate a time.
